[build]
  command = "cd my-react-app && npm install && npm run build && cd ../backend && npm install && npm run build"
  publish = "my-react-app/build"  # Adjust the publish directory based on your project's structure

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
